#ifndef BUCLE_H_INCLUDED
#define BUCLE_H_INCLUDED
#define COLUMNAS 5
#define FILAS 3
#define MAX_CARTONES 3

//PRE: DOS MATRICES DE TRES DIMENSIONES, UN VECTOR DE 90 POSICIONES CON NUMEROS DE 1 A 90 SIN REPETIR, UN ENTERO DE 1 A 3, Y DOS ESTRUCTURAS JUGADOR
//POST: COMPARA LOS NUMEROS DEL VECTOR CON LOS DE LAS MATRICES, ACUMULA LOS PUNTAJES DE LOS JUGADORES Y LOS GUARDA EN UN ARCHIVO
void bucleDeJuego (int m[][FILAS][COLUMNAS], int mpc[][FILAS][COLUMNAS], int v[], int cartones, Jugador j, Jugador pc);

//PRE: UNA MATRIZ DE ENTEROS DE TRES DIMENSIONES Y UN ENTERO DE 1 A 3
//POST: DEVUELVE 0 SI NO HAY LINEA, DEVUELVE 1 SI HAY LINEA
int cantarLinea(int m[][FILAS][COLUMNAS],int cartones);

//PRE: UNA MATRIZ DE ENTEROS DE TRES DIMENSIONES Y UN ENTERO DE 1 A 3
//POST: DEVUELVE 0 SI NO HAY LINEA, DEVUELVE 1 SI HAY LINEA
int cantarColumna(int m[][FILAS][COLUMNAS],int cartones);

//PRE: UNA MATRIZ DE ENTEROS DE TRES DIMENSIONES Y UN ENTERO DE 1 A 3
//POST: DEVUELVE 0 SI NO HAY LINEA, DEVUELVE 1 SI HAY LINEA
int cantarBingo(int m[][FILAS][COLUMNAS],int cartones);

#endif // BUCLE_H_INCLUDED
